In [6]:
import numpy as np

In [7]:
import pandas as pd

In [10]:
df = pd.read_excel('/content/Definitiv screening steel-copper lap joints V1.1.xlsx')

In [11]:
df

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,no,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,no,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,no,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,no,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,no,2232.0,320.0,149.0,102.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2,1200,1.2,20,-2,15,0.5,4,32,yes,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,no,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,no,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,no,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,no,1861.0,0.0,0.0,15.0,NaN,NaN

In [12]:
df.head()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
0,1,1050,1.0,15,0,0,0.6,1,8,no,2097.0,286.0,110.0,58.0,NaN,NaN
1,1,1050,1.0,15,0,0,0.6,1,16,no,2069.0,384.0,149.0,85.0,NaN,NaN
2,1,1050,1.0,15,0,0,0.6,1,24,no,2043.0,385.0,177.0,91.0,NaN,NaN
3,1,1050,1.0,15,0,0,0.6,1,32,no,2010.0,414.0,164.0,58.0,NaN,NaN
4,1,1050,1.0,15,0,0,0.6,2,8,no,2232.0,320.0,149.0,102.0,NaN,NaN

In [14]:
df.tail()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),cracking in the weld metal (yes/no),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
355,2,1200,1.2,20,-2,15,0.5,4,32,yes,1645.0,484.0,454.0,17.0,3.0,288.57
356,2,1200,1.2,20,-2,15,0.5,5,8,no,2035.0,151.0,14.0,33.0,NaN,NaN
357,2,1200,1.2,20,-2,15,0.5,5,16,no,2007.0,109.0,12.0,31.0,NaN,NaN
358,2,1200,1.2,20,-2,15,0.5,5,24,no,1915.0,61.0,9.0,21.0,NaN,NaN
359,2,1200,1.2,20,-2,15,0.5,5,32,no,1861.0,0.0,0.0,15.0,NaN,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   block                                360 non-null    int64
 1   power (W)                            360 non-null    int64
 2   welding speed (m/min)                360 non-null    float64
 3   gas flow rate (l/min)                360 non-null    int64
 4   focal position (mm)                  360 non-null    int64
 5   angular position (°)                 360 non-null    int64
 6   material strenght steel (mm)         360 non-null    float64
 7   weldnumber                           360 non-null    int64
 8   position on the weld path (mm)       360 non-null    int64
 9   cracking in the weld metal (yes/no)  360 non-null    object
 10  weld width steel (µm)                300 non-null    float64
 11  weld width copper (µm)               300 non-null    float64
 12  weld depth copper (µm)               300 non-null    float64
 13  gap (µm)                             300 non-null    float64
 14  count of cracks                      51 non-null     float64
 15  average crack lenght (µm)            51 non-null     float64
dtypes: float64(8), int64(7), object(1)
memory usage: 45.1+ KB

In [17]:
df.shape

(360, 16)

In [18]:
df.describe()

,block,power (W),welding speed (m/min),gas flow rate (l/min),focal position (mm),angular position (°),material strenght steel (mm),weldnumber,position on the weld path (mm),weld width steel (µm),weld width copper (µm),weld depth copper (µm),gap (µm),count of cracks,average crack lenght (µm)
count,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.00000,300.000000,300.000000,300.000000,300.00000,51.000000,51.000000
mean,1.500000,1050.000000,1.000000,15.000000,0.000000,0.000000,0.600000,3.000000,20.00000,2074.076667,258.603333,134.120000,78.20000,4.333333,359.715098
std,0.500696,132.471682,0.176629,4.415723,1.766289,13.247168,0.088314,1.416182,8.95672,364.899644,182.594767,173.243789,57.45692,2.055886,118.567927
min,1.000000,900.000000,0.800000,10.000000,-2.000000,-15.000000,0.500000,1.000000,8.00000,0.000000,0.000000,0.000000,10.00000,1.000000,146.790000
25%,1.000000,900.000000,0.800000,10.000000,-2.000000,-15.000000,0.500000,2.000000,14.00000,1868.500000,95.500000,9.000000,35.00000,3.000000,264.020000
50%,1.500000,1050.000000,1.000000,15.000000,0.000000,0.000000,0.600000,3.000000,20.00000,2016.500000,258.500000,58.500000,64.00000,4.000000,334.600000
75%,2.000000,1200.000000,1.200000,20.000000,2.000000,15.000000,0.700000,4.000000,26.00000,2255.500000,394.000000,163.250000,102.00000,6.000000,457.705000
max,2.000000,1200.000000,1.200000,20.000000,2.000000,15.000000,0.700000,5.000000,32.00000,3637.000000,629.000000,705.000000,502.00000,10.000000,647.630000

In [19]:
df.isnull().sum()

block                                    0
power (W)                                0
welding speed (m/min)                    0
gas flow rate (l/min)                    0
focal position (mm)                      0
angular position (°)                     0
material strenght steel (mm)             0
weldnumber                               0
position on the weld path (mm)           0
cracking in the weld metal (yes/no)      0
weld width steel (µm)                   60
weld width copper (µm)                  60
weld depth copper (µm)                  60
gap (µm)                                60
count of cracks                        309
average crack lenght (µm)              309
dtype: int64